 alter table produtos add column valor_compra decimal(12,4);
alter table produtos add column valor_delivery decimal(12,4);
alter table produtos add column tempo_preparo integer default null;
alter table produtos add column referencia varchar(20) default null;
alter table produtos add column adRemICMSRet decimal(10,4) default 0;
alter table produtos add column pBio decimal(10,4) default 0;
alter table produtos add column tipo_servico boolean default 0;
alter table produtos add column delivery boolean default 0;
alter table produtos add column cUFOrig varchar(2) default null;
alter table produtos add column pOrig decimal(5,2) default 0;
alter table produtos add column indImport integer default 0;
alter table produtos add column codigo_anp varchar(10) default null;
alter table produtos add column perc_glp decimal(5,2) default 0;
alter table produtos add column perc_gnn decimal(5,2) default 0;
alter table produtos add column perc_gni decimal(5,2) default 0;
alter table produtos add column valor_partida decimal(10, 2) default 0;
alter table produtos add column unidade_tributavel varchar(4) default '';
alter table produtos add column quantidade_tributavel decimal(10, 2) default 0;
alter table produtos add column composto boolean default 0;
alter table produtos add column estoque_minimo decimal(5, 2) default 0;
alter table produtos add column alerta_validade varchar(255) default '';
alter table produtos add column referencia_balanca integer default null;
alter table produtos add column variacao_modelo_id integer default null;
alter table produtos add column cfop_entrada_estadual varchar(4) default null;
alter table produtos add column cfop_entrada_outro_estado varchar(4) default null;
alter table users add column sidebar_active boolean default 1;
alter table users add column notificacao_cardapio boolean default 0;
alter table users add column notificacao_marketplace boolean default 0;
alter table users add column tipo_contador boolean default 0;
alter table empresas add column logo varchar(100) default null;
alter table empresas add column tipo_contador boolean default 0;
alter table empresas add column exclusao_icms_pis_cofins boolean default 0;
alter table empresas add column limite_cadastro_empresas integer default 0;
alter table empresas add column percentual_comissao decimal(10,2) default 0;
alter table empresas add column empresa_selecionada integer default null;
alter table categoria_produtos add column tipo_pizza boolean default 0;
alter table categoria_produtos add column delivery boolean default 0;
alter table padrao_tributacao_produtos add column codigo_beneficio_fiscal varchar(10) default null;
alter table padrao_tributacao_produtos add column cfop_entrada_estadual varchar(4) default null;
alter table padrao_tributacao_produtos add column cfop_entrada_outro_estado varchar(4) default null;
alter table padrao_tributacao_produtos add column padrao boolean default 0;
alter table caixas add column data_fechamento timestamp default null;
alter table caixas add column valor_fechamento decimal(10,2) default 0;
alter table caixas add column valor_dinheiro decimal(10,2) default 0;
alter table caixas add column valor_cheque decimal(10,2) default 0;
alter table caixas add column valor_outros decimal(10,2) default 0;
alter table planos add column modulos text;
alter table planos add column visivel_contadores boolean default 0;
alter table clientes add column senha varchar(200) default null;
alter table clientes add column token integer default null;
alter table clientes add column valor_cashback decimal(10,2) default 0;
alter table nves add column orcamento boolean default 0;
alter table nves add column ref_orcamento integer default null;
alter table nves add column data_emissao_saida date default null;
alter table nves add column data_emissao_retroativa date default null;
alter table nves add column bandeira_cartao varchar(2) default null;
alter table nves add column cnpj_cartao varchar(18) default null;
alter table nves add column cAut_cartao varchar(18) default null;
alter table nves add column tipo_pagamento varchar(2) default '';
alter table nfces add column bandeira_cartao varchar(2) default 99;
alter table nfces add column cnpj_cartao varchar(18) default null;
alter table nfces add column cAut_cartao varchar(18) default null;
alter table nfces add column gerar_conta_receber boolean default 0;
alter table nfces add column valor_cashback decimal(10,2) default null;
alter table item_nves add column lote varchar(30) default null;
alter table item_nves add column data_vencimento date default null;
alter table item_nves add column variacao_id integer default null;
alter table item_nfces add column codigo_beneficio_fiscal varchar(10) default null;
alter table item_nfces add column variacao_id integer default null;
alter table configuracao_supers add column sms_key varchar(120) default null;
alter table configuracao_supers add column token_whatsapp varchar(120) default null;
alter table estoques add column produto_variacao_id integer default null;
alter table movimentacao_produtos add column produto_variacao_id integer default null;
alter table ctes add column status_pagamento boolean default 0;
alter table ctes add column api boolean default 0;
alter table conta_pagars add column caixa_id bigint(20) default null;
alter table conta_recebers add column caixa_id bigint(20) default null;
alter table funcionarios add column comissao decimal(10 ,2) default 0;
alter table funcionarios add column salario decimal(10 ,2) default 0;
alter table comissao_vendas add column valor_venda decimal(10,2) default 0;
alter table mdves add column latitude_carregamento varchar(15) default '';
alter table mdves add column longitude_carregamento varchar(15) default '';
alter table mdves add column latitude_descarregamento varchar(15) default '';
alter table mdves add column longitude_descarregamento varchar(15) default '';
alter table mdves add column estado_emissao enum('novo', 'aprovado', 'rejeitado', 'cancelado');
alter table mdves add column mdfe_numero integer default null;
alter table categoria_servicos add column imagem varchar(25) default '';
alter table servicos add column imagem varchar(25) default null;
alter table servicos add column status boolean default 1;
alter table interrupcoes add column motivo varchar(50) default null;
alter table servico_os add column valor decimal(10, 2) default 0;
alter table servico_os add column subtotal decimal(10, 2) default 0;
alter table produto_os add column valor decimal(10, 2) default 0;
alter table produto_os add column subtotal decimal(10, 2) default 0;
alter table agendamentos add column prioridade enum('baixa', 'media', 'alta') default 'baixa';
alter table tamanho_pizzas add column nome_en varchar(50) default null;
alter table tamanho_pizzas add column nome_es varchar(50) default null;
alter table pedidos add column em_atendimento boolean default 1;
alter table pedidos add column nfce_id integer default null;
alter table produtos add column tempo_preparo integer default null;
alter table produtos add column ponto_carne varchar(30) default null;
alter table item_pedidos add column tamanho_id integer default null;
alter table configuracao_cardapios add column valor_pizza enum('divide', 'valor_maior') default 'divide';
alter table cte_os add column data_viagem varchar(10) default '';
alter table cte_os add column horario_viagem varchar(5) default '';
alter table cte_os add column cfop varchar(4) default null;
alter table cte_os add column recibo varchar(30) default null;
alter table config_gerals add column confirmar_itens_prevenda boolean default 0;
alter table bairro_deliveries add column status boolean default 1;
alter table market_place_configs add column tipo_entrega varchar(30) default '';
alter table pedido_deliveries add column finalizado boolean default 0;
alter table pedido_deliveries add column nfce_id integer default null;
alter table produtos add column ecommerce boolean default 0;
alter table produtos add column valor_ecommerce decimal(12,4) default null;
alter table produtos add column percentual_desconto integer default null;
alter table produtos add column descricao_ecommerce varchar(255) default null;
alter table produtos add column largura decimal(8, 2) default null;
alter table produtos add column comprimento decimal(8, 2) default null;
alter table produtos add column altura decimal(8, 2) default null;
alter table produtos add column peso decimal(12, 3) default null;
alter table categoria_produtos add column ecommerce boolean default 0;
alter table produtos add column destaque_ecommerce boolean default 0;
alter table produtos add column hash_ecommerce varchar(50) default null;
alter table produtos add column texto_ecommerce text;
alter table configuracao_supers add column usuario_correios varchar(30) default null;
alter table configuracao_supers add column codigo_acesso_correios varchar(100) default null;
alter table configuracao_supers add column cartao_postagem_correios varchar(100) default null;
alter table configuracao_supers add column token_correios text;
alter table configuracao_supers add column token_expira_correios varchar(30) default null;
alter table configuracao_supers add column dr_correios varchar(30) default null;
alter table configuracao_supers add column contrato_correios varchar(30) default null;
alter table categoria_produtos add column hash_ecommerce varchar(50) default null;
alter table users add column notificacao_ecommerce boolean default 0;
alter table planos add column auto_cadastro boolean default 0;
alter table clientes add column uid varchar(30) default null;
alter table clientes add column status boolean default 1;
alter table config_gerals modify column balanca_digito_verificador integer default null;
alter table empresas add column numero_ultima_nfse integer default null;
alter table empresas add column numero_serie_nfse integer default null;
alter table servicos add column codigo_tributacao_municipio varchar(30) default null;
alter table nfces add column lista_id integer default null;
alter table pre_vendas add column lista_id integer default null;
alter table item_pre_vendas add column variacao_id integer default null;
alter table ordem_servicos add column codigo_sequencial integer default null;
alter table configuracao_supers add column token_auth_nfse varchar(255) default null;
alter table empresas add column token_nfse varchar(200) default null;
alter table config_gerals add column notificacoes text;
alter table market_place_configs add column loja_id varchar(15) default null;
alter table produtos add column destaque_delivery boolean default 0;
alter table categoria_produtos add column hash_delivery varchar(50) default null;
alter table produtos add column hash_delivery varchar(50) default null;
alter table produtos add column texto_delivery text;
alter table nves add column numero_sequencial integer default null;
alter table nfces add column numero_sequencial integer default null;
alter table market_place_configs add column email varchar(80) default null;
alter table market_place_configs add column cor_principal varchar(10) default null;
alter table ecommerce_configs add column dados_deposito text;
alter table pedido_ecommerces modify column tipo_pagamento enum('cartao', 'pix', 'boleto', 'deposito');
alter table empresas add column aut_xml varchar(18) default null;
alter table pedido_ecommerces add column comprovante varchar(25) default null;
alter table planos add column segmento_id integer default null;
alter table configuracao_supers add column timeout_nfe integer default 8;
alter table configuracao_supers add column timeout_nfce integer default 8;
alter table configuracao_supers add column timeout_cte integer default 8;
alter table configuracao_supers add column timeout_mdfe integer default 8;
alter table produtos add column mercado_livre_id varchar(20) default null;
alter table produtos add column mercado_livre_link varchar(255) default null;
alter table produtos add column mercado_livre_valor decimal(12, 4) default null;
alter table produtos add column mercado_livre_categoria varchar(20) default null;
alter table produtos add column condicao_mercado_livre varchar(20) default null;
alter table produtos add column quantidade_mercado_livre integer default null;
alter table produtos add column mercado_livre_tipo_publicacao varchar(20) default null;
alter table produtos add column mercado_livre_youtube varchar(100) default null;
alter table produtos add column mercado_livre_descricao text;
alter table mercado_livre_configs add column refresh_token varchar(255) default null;
alter table mercado_livre_configs add column token_expira bigint default null;
alter table mercado_livre_perguntas add column resposta text;
alter table pedido_mercado_livres add column codigo_rastreamento varchar(30) default null;
alter table planos add column fiscal boolean default 1;
alter table nves add column crt integer default null;
alter table caixas add column conta_empresa_id integer default null;
alter table sangria_caixas add column conta_empresa_id integer default null;
alter table suprimento_caixas add column conta_empresa_id integer default null;
alter table suprimento_caixas add column tipo_pagamento varchar(2) default null;
alter table produtos add column combo boolean default 0;
alter table produtos add column margem_combo decimal(5, 2) default 0;
alter table config_gerals add column margem_combo decimal(5,2) default 50;
alter table agendamentos add column nfce_id integer default null;
alter table nfces add column funcionario_id integer default null;
alter table produtos add column nuvem_shop_id varchar(20) default null;
alter table produtos add column nuvem_shop_valor decimal(12, 4) default null;
alter table produtos add column texto_nuvem_shop text;
alter table clientes add column nuvem_shop_id varchar(20) default null;
alter table produtos add column modBCST integer default null;
alter table produtos add column pMVAST decimal(5,2) default null;
alter table produtos add column pICMSST decimal(5,2) default null;
alter table produtos add column redBCST decimal(5,2) default null;
alter table padrao_tributacao_produtos add column modBCST integer default null;
alter table padrao_tributacao_produtos add column pMVAST decimal(5,2) default null;
alter table padrao_tributacao_produtos add column pICMSST decimal(5,2) default null;
alter table padrao_tributacao_produtos add column redBCST decimal(5,2) default null;
alter table conta_pagars add column local_id integer default null;
alter table conta_recebers add column local_id integer default null;
alter table nfces add column local_id integer default null;
alter table nves add column local_id integer default null;
alter table estoques add column local_id integer default null;
alter table ctes add column local_id integer default null;
alter table mdves add column local_id integer default null;
alter table cte_os add column local_id integer default null;
alter table caixas add column local_id integer default null;
alter table pre_vendas add column local_id integer default null;
alter table produtos modify column nome varchar(200);
alter table planos add column valor_implantacao decimal(10,2) default 0;
alter table nves add column signed_xml text default null;
alter table nfces add column signed_xml text default null;
alter table mdves add column tipo_modal integer default 1;
alter table reservas add column data_checkin_realizado timestamp default CURRENT_TIMESTAMP;
alter table consumo_reservas add column frigobar boolean default 0;
alter table categoria_produtos add column reserva boolean default 0;
alter table produtos add column reserva boolean default 0;
alter table reservas add column motivo_cancelamento text;
alter table servicos add column reserva boolean default 0;
alter table reservas add column nfe_id integer default null;
alter table item_nves add column vbc_icms decimal(10,2) default 0;
alter table item_nves add column vbc_pis decimal(10,2) default 0;
alter table item_nves add column vbc_cofins decimal(10,2) default 0;
alter table item_nves add column vbc_ipi decimal(10,2) default 0;
alter table reservas add column nfse_id integer default null;
alter table servicos add column padrao_reserva_nfse boolean default 0;
alter table categoria_servicos add column marketplace boolean default 0;
alter table servicos add column marketplace boolean default 0;
alter table categoria_servicos add column hash_delivery varchar(50) default null;
alter table servicos add column hash_delivery varchar(50) default null;
alter table servicos add column descricao text;
alter table produtos add column percentual_lucro decimal(10,2) default 0;
alter table config_gerals add column percentual_lucro_produto decimal(10,2) default 0;
alter table servicos add column destaque_marketplace boolean default null;
alter table nota_servicos add column gerar_conta_receber boolean default null;
alter table nota_servicos add column data_vencimento date default null;
alter table nota_servicos add column conta_receber_id integer default null;
alter table config_gerals add column tipos_pagamento_pdv text;
alter table movimentacao_produtos add column user_id integer default null;
alter table config_gerals add column senha_manipula_valor varchar(20) default null;
alter table config_gerals add column abrir_modal_cartao boolean default 1;
alter table nves add column user_id integer default null;
alter table nfces add column user_id integer default null;
alter table categoria_produtos add column categoria_id integer default null;
alter table produtos add column codigo_barras2 varchar(20) default null;
alter table produtos add column codigo_barras3 varchar(20) default null;
alter table produtos add column sub_categoria_id integer default null;
alter table config_gerals add column percentual_desconto_orcamento decimal(5,2) default null;
alter table clientes add column valor_credito decimal(10,2) default 0;
alter table conta_pagars add column arquivo varchar(25) default null;
alter table conta_recebers add column arquivo varchar(25) default null;
alter table produtos add column valor_atacado decimal(22,7) default 0;
alter table produtos add column quantidade_atacado integer default null;
alter table market_place_configs add column funcionamento_descricao varchar(100) default null;
alter table produtos add column oferta_delivery boolean default 0;
alter table carrinho_deliveries add column observacao varchar(200) default null;
alter table carrinho_deliveries add column tipo_pagamento varchar(20) default null;
alter table carrinho_deliveries add column troco_para decimal(10,2) default null;
alter table empresas modify column tributacao enum('MEI', 'Simples Nacional', 'Regime Normal', 'Simples Nacional, excesso sublimite de receita bruta');
alter table carrinho_deliveries add column tipo_entrega enum('delivery', 'retirada') default null;
alter table ordem_servicos add column caixa_id integer default null;
alter table nves add column contigencia boolean default 0;
alter table nfces add column contigencia boolean default 0;
alter table nfces add column reenvio_contigencia boolean default 0;
alter table pedidos add column funcionario_id integer default null;
alter table item_pedidos add column funcionario_id integer default null;
alter table config_gerals add column gerenciar_estoque boolean default 0;
alter table funcionarios add column codigo varchar(30) default null;
alter table nves add column data_entrega date default null;
alter table natureza_operacaos add column cst_csosn varchar(3) default null;
alter table natureza_operacaos add column cst_pis varchar(3) default null;
alter table natureza_operacaos add column cst_cofins varchar(3) default null;
alter table natureza_operacaos add column cst_ipi varchar(3) default null;
alter table natureza_operacaos add column cfop_estadual varchar(4) default null;
alter table natureza_operacaos add column cfop_outro_estado varchar(4) default null;
alter table natureza_operacaos add column cfop_entrada_estadual varchar(4) default null;
alter table natureza_operacaos add column cfop_entrada_outro_estado varchar(4) default null;
alter table natureza_operacaos add column perc_icms decimal(5, 2) default null;
alter table natureza_operacaos add column perc_pis decimal(5, 2) default null;
alter table natureza_operacaos add column perc_cofins decimal(5, 2) default null;
alter table natureza_operacaos add column perc_ipi decimal(5, 2) default null;
alter table produtos add column woocommerce_id varchar(20) default null;
alter table produtos add column woocommerce_slug varchar(80) default null;
alter table produtos add column woocommerce_link varchar(255) default null;
alter table produtos add column woocommerce_valor decimal(12, 4) default null;
alter table produtos add column woocommerce_type varchar(30) default null;
alter table produtos add column woocommerce_status varchar(30) default null;
alter table produtos add column woocommerce_descricao text;
alter table produtos add column woocommerce_stock_status varchar(30) default null;
alter table produtos add column categorias_woocommerce text;
alter table empresas add column observacao_padrao_nfe text;
alter table empresas add column observacao_padrao_nfce text;
alter table config_gerals add column agrupar_itens boolean default 0;
alter table movimentacao_produtos add column estoque_atual decimal(14,4) default 0;
alter table item_nves add column xPed varchar(30) default null;
alter table item_nves add column nItemPed varchar(30) default null;
alter table registro_tefs add column usuario_id integer default null;
alter table nves modify column observacao varchar(255) default null;    
alter table item_carrinho_deliveries add column observacao varchar(50) default null;
alter table item_carrinho_deliveries add column tamanho_id integer default null;
alter table planos add column maximo_usuarios integer default null;
alter table planos add column maximo_locais integer default null;
alter table produtos add column tipo_unico boolean default 0;
alter table natureza_operacaos add column padrao boolean default 0;
alter table produtos add column balanca_pdv boolean default 0;
alter table carrinho_deliveries add column fone varchar(20) default null;
alter table carrinho_deliveries add column cupom varchar(6) default null;
alter table config_gerals add column tipo_comissao enum('percentual_vendedor', 'percentual_margem') default 'percentual_vendedor';
alter table veiculos add column funcionario_id integer default null;
alter table configuracao_supers add column usar_resp_tecnico boolean default 0;
alter table clientes add column limite_credito decimal(10,2) default null;
alter table configuracao_supers add column token_integra_notas varchar(255) default null;
alter table nves add column funcionario_id integer default null;
alter table item_nves add column infAdProd varchar(200) default null;
alter table produtos add column mercado_livre_modelo varchar(100) default null;
alter table configuracao_supers add column token_api varchar(50) default null;
alter table nfces modify column observacao varchar(200) default null;
alter table natureza_operacaos add column sobrescrever_cfop boolean default 0;
alter table fretes add column numero_sequencial integer default null;
alter table fretes add column total_despesa decimal(12,2) default null;
alter table fretes modify column horario_inicio time default null;
alter table fretes modify column horario_fim time default null;
alter table fretes add column conta_receber_id integer default null;
alter table veiculos add column status boolean default 1;
alter table despesa_fretes add column conta_pagar_id integer default null;
alter table config_gerals add column modelo varchar(20) default 'light';
alter table config_gerals add column alerta_sonoro boolean default 1;
alter table empresas add column mensagem_aproveitamento_credito text;
alter table empresas add column perc_ap_cred decimal(10,2) default 0;
alter table item_carrinho_deliveries add column servico_id integer default null;
alter table item_carrinho_deliveries modify column produto_id bigint unsigned default null;
alter table funcionarios add column status boolean default 1;
alter table carrinho_deliveries add column funcionario_id_agendamento integer default null;
alter table carrinho_deliveries add column inicio_agendamento varchar(5) default null;
alter table carrinho_deliveries add column fim_agendamento varchar(5) default null;
alter table carrinho_deliveries add column data_agendamento date default null;
alter table item_pedido_deliveries add column servico_id integer default null;
alter table item_pedido_deliveries modify column produto_id bigint unsigned default null;
alter table pedido_deliveries add column funcionario_id_agendamento integer default null;
alter table pedido_deliveries add column inicio_agendamento varchar(5) default null;
alter table pedido_deliveries add column fim_agendamento varchar(5) default null;
alter table pedido_deliveries add column data_agendamento date default null;
alter table agendamentos add column pedido_delivery_id integer default null;
alter table item_nfces modify column quantidade decimal(12,3);
alter table item_nves modify column quantidade decimal(12,3);
alter table agendamentos add column msg_wpp_manha_horario boolean default 0;
alter table agendamentos add column msg_wpp_alerta_horario boolean default 0;
alter table produtos add column valor_minimo_venda decimal(12,4) default 0;
alter table servicos add column numero_sequencial integer default null;
alter table clientes add column lista_preco_id integer default null;
alter table interrupcoes add column status boolean default 1;
alter table localizacaos add column perc_ap_cred decimal(10,2) default 0;
alter table localizacaos add column mensagem_aproveitamento_credito text;
alter table users add column escolher_localidade_venda boolean default 0;
alter table conta_empresas add column local_id integer default null;
alter table produtos add column exportar_balanca boolean default 0;
alter table nfces add column chave_sat varchar(44) default null;
alter table config_gerals add column cabecalho_pdv boolean default 1;
alter table config_gerals add column regime_nfse integer default null;
alter table produtos add column referencia_xml varchar(50) default null;
alter table config_gerals add column mercadopago_public_key_pix varchar(120) default null;
alter table config_gerals add column mercadopago_access_token_pix varchar(120) default null;
alter table ordem_servicos add column local_id integer default null;
alter table ordem_servicos add column horario_entrega time default null;
alter table ordem_servicos add column convenio_id integer default null;
alter table carrinho_deliveries add column endereco_id integer default null;
alter table ordem_servicos add column status_entrega boolean default 0;
alter table ordem_servicos add column adiantamento decimal(10,2) default 0;
alter table item_nves add column pMVAST decimal(10,4) default null;
alter table item_nves add column vBCST decimal(10,2) default null;
alter table item_nves add column pICMSST decimal(10,2) default null;
alter table item_nves add column vICMSST decimal(10,2) default null;
alter table item_nves add column vBCFCPST decimal(10,2) default null;
alter table item_nves add column pFCPST decimal(10,2) default null;
alter table item_nves add column vFCPST decimal(10,2) default null;
alter table item_nves add column modBCST integer default null;
alter table produtos add column tipo_dimensao boolean default 0;
alter table produtos add column espessura decimal(8,2) default null;
alter table config_gerals add column definir_vendedor_pdv_off boolean default 0;
alter table config_gerals add column acessos_pdv_off varchar(255) default null;
alter table escritorio_contabils add column token_sieg varchar(255) default null;
alter table categoria_produtos add column _id_import integer default null;
alter table produtos add column _id_import integer default null;
alter table clientes add column _id_import integer default null;
alter table fornecedors add column _id_import integer default null;
alter table natureza_operacaos add column _id_import integer default null;
alter table transportadoras add column _id_import integer default null;
alter table config_gerals add column tipo_menu enum('vertical', 'horizontal') default 'vertical';
alter table config_gerals add column cor_menu enum('light', 'brand', 'dark') default 'light';
alter table config_gerals add column cor_top_bar enum('light', 'brand', 'dark') default 'light';
alter table users add column suporte boolean default 0;
alter table nfces add column valor_entrega decimal(10, 2) default 0;
alter table produtos add column observacao varchar(100) default null;
alter table produtos add column observacao2 varchar(100) default null;
alter table produtos add column observacao3 varchar(100) default null;
alter table produtos add column observacao4 varchar(100) default null;
alter table mdves modify column quantidade_carga decimal(16, 4) default 0;
alter table configuracao_supers add column asaas_token varchar(255) default null;
alter table configuracao_supers add column banco_plano enum('mercado_pago', 'asaas') default 'mercado_pago';
alter table servicos add column codigo_cnae varchar(30) default null;
alter table servicos add column natureza_operacao varchar(100) default null;
alter table servicos add column estado_local_prestacao_servico varchar(2) default null;
alter table servicos add column aliquota_ir decimal(7,2) default null;
alter table servicos add column aliquota_csll decimal(7,2) default null;
alter table servicos add column valor_deducoes decimal(16,7) default null;
alter table servicos add column desconto_incondicional decimal(16,7) default null;
alter table servicos add column desconto_condicional decimal(16,7) default null;
alter table servicos add column outras_retencoes decimal(16,7) default null;
alter table produtos add column tipo_producao boolean default 0;
alter table configuracao_supers add column auto_cadastro boolean default 1;
alter table config_gerals add column usar_ibpt boolean default 1;
alter table item_producaos add column observacao varchar(100) default null;
alter table item_producaos add column dimensao varchar(100) default null;
alter table configuracao_cardapios add column incluir_servico boolean default 0;
alter table item_nves modify column quantidade decimal(12,4);
alter table item_nfces modify column quantidade decimal(12,4);
alter table config_gerals add column casas_decimais_quantidade integer default 2;
alter table cash_back_configs add column mensagem_automatica_5_dias text;
alter table cash_back_configs add column mensagem_automatica_1_dia text;
alter table localizacaos add column token_whatsapp varchar(120) default null;
alter table produtos add column numero_sequencial integer default null;
alter table categoria_produtos add column status boolean default 1;
alter table users add column status boolean default 1;
alter table config_gerals add column definir_vendedor_pdv boolean default 0;
alter table config_gerals add column cliente_padrao_pdv_off integer default null;
alter table conta_recebers add column motivo_estorno varchar(255) default null;
alter table conta_pagars add column motivo_estorno varchar(255) default null;
alter table configuracao_supers add column asaas_token_boleto varchar(255) default null;
alter table configuracao_supers add column receber_com_boleto boolean default 0;
alter table empresas add column receber_com_boleto boolean default 0;
alter table empresas add column dia_vencimento_boleto integer default null;
alter table empresas add column asaas_id varchar(20) default null;
alter table configuracao_supers add column percentual_juros_padrao_boleto decimal(5,2) default 0;
alter table configuracao_supers add column percentual_multa_padrao_boleto decimal(5,2) default 0;
alter table configuracao_supers add column dias_atraso_suspender_boleto integer default null;
alter table configuracao_supers add column sandbox_boleto boolean default 1;
alter table clientes add column id_estrangeiro varchar(30) default null;
alter table clientes add column codigo_pais varchar(4) default null;
alter table fornecedors add column id_estrangeiro varchar(30) default null;
alter table fornecedors add column codigo_pais varchar(4) default null;
alter table config_gerals add column gerar_conta_receber_padrao boolean default 1;
alter table ctes add column tipo_servico integer default null;
alter table ctes add column doc_anterior varchar(20) default null;
alter table ctes add column emitente_anterior varchar(100) default null;
alter table ctes add column tp_doc_anterior varchar(2) default null;
alter table ctes add column serie_anterior varchar(3) default null;
alter table ctes add column n_doc_anterior varchar(8) default null;
alter table ctes add column data_emissao_anterior date default null;
alter table ctes add column uf_anterior varchar(2) default null;
alter table ctes add column ie_anterior varchar(20) default null;
alter table ctes add column referencia_cte varchar(44) default null;
alter table lista_precos add column status boolean default 1;
alter table funcionarios add column permite_alterar_valor_app boolean default 1;
alter table contrato_empresas add column texto text;
alter table ctes add column cpf_cnpj_tomador varchar(18) default null;
alter table ctes add column ie_tomador varchar(15) default null;
alter table ctes add column razao_social_tomador varchar(60) default null;
alter table ctes add column nome_fantasia_tomador varchar(60) default null;
alter table ctes add column telefone_tomador varchar(20) default null;
alter table ctes add column email_tomador varchar(60) default null;
alter table ecommerce_configs add column cor_principal varchar(10) default '#000';
alter table config_gerals add column mensagem_padrao_impressao_venda text;
alter table config_gerals add column mensagem_padrao_impressao_os text;
alter table config_gerals add column ultimo_codigo_produto integer default 0;
alter table config_gerals add column ultimo_codigo_cliente integer default 0;
alter table config_gerals add column ultimo_codigo_fornecedor integer default 0;
alter table fornecedors add column numero_sequencial integer default null;
alter table clientes add column numero_sequencial integer default null;
alter table config_gerals add column app_valor_aprazo boolean default 0;
alter table produtos add column valor_prazo decimal(12,4) default null;
alter table config_gerals add column impressao_sem_janela_cupom boolean default 0;
alter table item_pedidos add column impresso boolean default 0;
alter table item_pedido_deliveries add column impresso boolean default 0;
alter table pedido_deliveries add column numero_sequencial integer default null;
alter table configuracao_supers add column usuario_alterar_plano boolean default 1;
alter table adicionals add column categoria_id integer default null;
alter table pedidos add column acrescimo decimal(10,2) default 0;
alter table configuracao_cardapios add column percentual_taxa_servico decimal(5,2) default 0;
alter table config_gerals add column alterar_valor_pdv_off boolean default 0;
alter table configuracao_supers add column info_topo_menu boolean default 1;
alter table configuracao_supers add column dias_alerta_boleto integer default 10;
alter table ifood_configs add column merchantUUID varchar(40) default null;
alter table produtos add column ifood_id varchar(50) default null;
alter table empresas add column token_ibpt varchar(200) default null;
alter table produtos add column vendizap_id varchar(50) default null;
alter table configuracao_supers add column tema_padrao enum('light', 'dark') default 'light';
alter table users add column tema_padrao varchar(10) default null;
alter table produtos add column vendizap_valor decimal(12, 4) default null;
alter table variacao_modelos add column vendizap_id varchar(50) default null;
alter table variacao_modelo_items add column vendizap_id varchar(50) default null;
alter table pedidos add column mesa_id integer default null;
alter table pedidos add column local_pedido varchar(10) default null;
alter table configuracao_cardapios add column qr_code_mesa boolean default 0;
alter table configuracao_cardapios add column cor_principal varchar(10) default null;
alter table produtos add column destaque_cardapio boolean default 0;
alter table produtos add column oferta_cardapio boolean default 0;
alter table pedidos add column session_cart_cardapio varchar(30) default null;
alter table carrinho_cardapios add column cliente_nome varchar(50) default null;
alter table produto_variacaos add column variacao_modelo_item_id integer default null;
alter table pedidos add column confirma_mesa boolean default 1;
alter table produtos add column sub_variacao_modelo_id integer default null;
alter table configuracao_supers add column duplicar_cpf_cnpj boolean default 1;
alter table users add column finalizacao_pdv varchar(25) default null;
alter table item_pedidos add column nome_cardapio varchar(60) default null;
alter table item_pedidos add column telefone_cardapio varchar(20) default null;
alter table item_pedidos add column finalizado_pdv boolean default 0;
alter table pedidos add column session_cart_user varchar(30) default null;
alter table carrinho_cardapios add column session_cart_user varchar(30) default null;
alter table configuracao_cardapios add column limite_pessoas_qr_code integer default null;
alter table agendamentos add column numero_sequencial integer default null;
alter table conta_recebers add column categoria_conta_id integer default null;
alter table conta_pagars add column categoria_conta_id integer default null;
alter table ordem_servicos add column veiculo_id integer default null;
alter table nfces add column placa varchar(9) default null;
alter table nfces add column uf varchar(2) default null;
alter table nfces add column numeracao_volumes varchar(20) default null;
alter table nfces add column especie varchar(20) default null;
alter table nfces add column peso_liquido decimal(8, 3) default null;
alter table nfces add column peso_bruto decimal(8, 3) default null;
alter table nfces add column valor_frete decimal(12, 2) default null;
alter table nfces add column transportadora_id integer default null;
alter table nfces add column tipo integer default null;
alter table nfces add column qtd_volumes integer default null;
alter table clientes add column data_nascimento date default null;
alter table conta_recebers add column valor_original decimal(16,7) default null;
alter table conta_recebers add column recebimento_parcial boolean default 0;
alter table conta_pagars add column desconto decimal(16, 7) default null;
alter table conta_pagars add column acrescimo decimal(16, 7) default null;
alter table conta_recebers add column observacao2 varchar(100) default null;
alter table conta_recebers add column observacao3 varchar(100) default null;
alter table conta_pagars add column observacao2 varchar(100) default null;
alter table conta_pagars add column observacao3 varchar(100) default null;
alter table config_gerals add column resp_tec_email varchar(80) default null;
alter table config_gerals add column resp_tec_cpf_cnpj varchar(18) default null;
alter table config_gerals add column resp_tec_nome varchar(60) default null;
alter table config_gerals add column resp_tec_telefone varchar(20) default null;
alter table modelo_etiquetas add column distancia_entre_linhas decimal(7,2) default 0;
alter table config_gerals add column limitar_credito_cliente boolean default 0;
alter table market_place_configs add column token_whatsapp varchar(120) default null;
alter table item_ordem_producaos add column cliente_id integer default null;
alter table item_ordem_producaos MODIFY column item_producao_id bigint unsigned default null;
alter table item_ordem_producaos add column numero_pedido varchar(100) default null;
alter table config_gerals add column documento_pdv varchar(4) default 'nfce';
alter table config_gerals add column numero_inicial_comanda integer default null;
alter table config_gerals add column numero_final_comanda integer default null;
alter table pedidos add column desconto decimal(10,2) default 0;
alter table fatura_reservas add column conta_receber_id integer default null;
alter table config_gerals add column corrigir_numeracao_fiscal boolean default 1;
alter table item_nfces add column tamanho_id integer default null;
alter table categoria_produtos add column status boolean default 1;
alter table item_nfces add column observacao varchar(255) default null;
alter table nves add column nome_entrega varchar(60) default null;
alter table nves add column documento_entrega varchar(20) default null;
alter table nves add column rua_entrega varchar(60) default null;
alter table nves add column cep_entrega varchar(9) default null;
alter table nves add column numero_entrega varchar(10) default null;
alter table nves add column bairro_entrega varchar(40) default null;
alter table nves add column complemento_entrega varchar(100) default null;
alter table nves add column cidade_id_entrega integer default null;
alter table cotacaos add column planejamento_id integer default null;
alter table planejamento_custos add column desconto decimal(14,2) default null;
alter table planejamento_custos add column frete decimal(14,2) default null;
alter table produto_planejamento_custos add column peso_especifico decimal(10,2) default null;
alter table produto_planejamento_custos add column calculo decimal(14,4) default null;
alter table config_gerals add column gerar_conta_pagar_padrao boolean default 1;
alter table modelo_etiquetas add column referencia boolean default 0;
alter table modelo_etiquetas add column valor_atacado boolean default 0;
alter table produtos add column peso_bruto decimal(12, 3) default null;
alter table cotacaos add column observacao_frete varchar(200) default null;
alter table cotacaos add column valor_frete decimal(10,2) default null;
alter table planos add column contador_id integer default null;
alter table plano_empresas add column contador_id integer default null;
alter table nves add column marca varchar(30) default null;
alter table planejamento_custos add column codigo_material varchar(60) default null;
alter table planejamento_custos add column equipamento varchar(200) default null;
alter table planejamento_custos add column desenho varchar(200) default null;
alter table planejamento_custos add column material varchar(200) default null;
alter table planejamento_custos add column quantidade decimal(10,2) default null;
alter table planejamento_custos add column unidade varchar(20) default null;
alter table planejamento_custos add column projeto_id integer default null;
alter table ctes add column tipo_cte integer default 0;
alter table configuracao_cardapios add column confirma_mesa boolean default 0;
alter table lista_precos add column valor_alteracao decimal(10,2) default 0;
alter table impressora_pedidos add column requisicao_segundos integer default 15;
alter table empresas add column cadastrar_planos boolean default 0;
alter table produtos add column local_armazenamento varchar(200) default null;
alter table produto_planejamento_custos add column peso_bruto decimal(10,2) default null;
alter table item_proposta_planejamento_custos add column peso_bruto decimal(10,2) default null;
alter table config_gerals add column home_componentes varchar(255) default '[]';
alter table config_gerals modify column home_componentes text;
alter table config_gerals add column token_whatsapp varchar(120) default null;
alter table produtos add column pICMSEfet decimal(5,2) default null;
alter table produtos add column pRedBCEfet decimal(5,2) default null;
alter table item_nves add column nDI varchar(30) default null;
alter table item_nves add column dDI date default null;
alter table item_nves add column dDesemb date default null;
alter table item_nves add column tpViaTransp varchar(2) default null;
alter table item_nves add column vAFRMM decimal(12,2) default null;
alter table item_nves add column tpIntermedio varchar(2) default null;
alter table item_nves add column cpf_cnpj_di varchar(18) default null;
alter table item_nves add column UFTerceiro varchar(2) default null;
alter table item_nves add column cExportador varchar(30) default null;
alter table item_nves add column nAdicao varchar(10) default null;
alter table item_nves add column cFabricante varchar(20) default null;
alter table item_nves add column cidade_desembarque_id integer default null;
alter table item_nves add column vBCII decimal(10,2) default null;
alter table item_nves add column vDespAdu decimal(10,2) default null;
alter table item_nves add column vII decimal(10,2) default null;
alter table item_nves add column vIOF decimal(10,2) default null;
alter table conta_recebers add column referencia varchar(60) default null;
alter table conta_pagars add column referencia varchar(60) default null;
alter table conta_pagars add column conta_empresa_id integer default null;
alter table conta_recebers add column conta_empresa_id integer default null;
alter table produtos add column cst_ibscbs varchar(3) default null;
alter table produtos add column cclass_trib varchar(10) default null;
alter table produtos add column perc_ibs_uf decimal(10,2) default 0;
alter table produtos add column perc_ibs_mun decimal(10,2) default 0;
alter table produtos add column perc_cbs decimal(10,2) default 0;
alter table produtos add column perc_dif decimal(10,2) default 0;
alter table config_gerals add column small_header_user varchar(50) default 'small-4.jpg';
alter table configuracao_supers add column email_aviso_novo_cadastro varchar(120) default null;
alter table produtos add column tipo_item_sped varchar(2) default null;
alter table item_conta_empresas add column cliente_id integer default null;
alter table item_conta_empresas add column fornecedor_id integer default null;
alter table item_conta_empresas add column numero_documento varchar(100) default null;
alter table item_conta_empresas add column categoria_id integer default null;
alter table item_conta_empresas add column conta_pagar_id integer default null;
alter table item_conta_empresas add column conta_receber_id integer default null;
alter table registro_tefs add column finalizacao varchar(30) default null;
alter table item_nves add column descricao varchar(200) default null;
alter table manifesto_dves add column tpNF integer default null;
alter table configuracao_supers add column cobrar_apos_auto_cadastro boolean default 0;
alter table planos add column descricao_curta varchar(200) default null;
alter table planos add column dias_teste integer default null;
alter table users add column plano_auto_cadastro integer default null;
alter table config_gerals add column mensagem_wpp_link text;
alter table config_gerals add column status_wpp_link boolean default 0;
alter table config_gerals add column enviar_danfe_wpp_link boolean default 0;
alter table config_gerals add column enviar_xml_wpp_link boolean default 0;
alter table config_gerals add column enviar_pedido_a4_wpp_link boolean default 0;
alter table mdves add column nome_pagador varchar(100) default null;
alter table mdves add column documento_pagador varchar(20) default null;
alter table mdves add column ind_pag varchar(2) default null;
alter table mdves add column valor_transporte decimal(10,2) default null;
alter table configuracao_supers add column landing_page boolean default 0;
alter table config_gerals add column produtos_exibe_tabela boolean default 1;
alter table config_gerals add column itens_por_pagina integer default 30;
alter table clientes add column imagem varchar(25) default null;
alter table config_gerals add column clientes_exibe_tabela boolean default 1;
alter table padrao_tributacao_produtos add column cst_ibscbs varchar(3) default null;
alter table padrao_tributacao_produtos add column cclass_trib varchar(10) default null;
alter table padrao_tributacao_produtos add column perc_ibs_uf decimal(10,2) default null;
alter table padrao_tributacao_produtos add column perc_ibs_mun decimal(10,2) default null;
alter table padrao_tributacao_produtos add column perc_cbs decimal(10,2) default null;
alter table padrao_tributacao_produtos add column perc_dif decimal(10,2) default null;
alter table padrao_tributacao_produto_supers add column cst_ibscbs varchar(3) default null;
alter table padrao_tributacao_produto_supers add column cclass_trib varchar(10) default null;
alter table padrao_tributacao_produto_supers add column perc_ibs_uf decimal(10,2) default null;
alter table padrao_tributacao_produto_supers add column perc_ibs_mun decimal(10,2) default null;
alter table padrao_tributacao_produto_supers add column perc_cbs decimal(10,2) default null;
alter table padrao_tributacao_produto_supers add column perc_dif decimal(10,2) default null;
alter table produtos add column prazo_garantia integer default null;
alter table item_nves add column vICMSSubstituto decimal(10,2) default null;
alter table natureza_operacaos add column movimentar_estoque boolean default 1;
alter table mensagem_padrao_crms add column mensagem_para_agendamento boolean default 0;
alter table mensagem_padrao_crms add column dias_apos_agendamento integer default 0;
alter table ordem_servicos add column hash_link varchar(30) default null;
alter table garantias add column servico_id integer default null;
alter table garantias modify column produto_id bigint(20) UNSIGNED null;
alter table ordem_servicos add column tipo_servico varchar(30) default null;
alter table ordem_servicos add column diagnostico_cliente text;
alter table ordem_servicos add column diagnostico_tecnico text;
alter table ordem_servicos add column defeito_encontrado text;
alter table config_gerals add column tipo_ordem_servico varchar(50) default 'normal';
alter table ordem_servicos add column equipamento varchar(100) default null;
alter table ordem_servicos add column numero_serie varchar(100) default null;
alter table ordem_servicos add column cor varchar(30) default null;
alter table ordem_servicos add column faturada boolean default 0;
alter table servicos add column prazo_garantia integer default null;
alter table conta_recebers add column ordem_servico_id integer default null;
alter table garantias add column ordem_servico_id integer default null;
alter table empresas add column substituto_tributario boolean default 0;
alter table localizacaos add column substituto_tributario boolean default 0;
alter table item_inventarios modify column estado varchar(15) default null;
alter table trocas add column nfe_id integer default null;
alter table trocas add column caixa_id integer default null;
ALTER TABLE trocas MODIFY COLUMN nfce_id BIGINT UNSIGNED NULL;
alter table item_trocas add column valor_unitario decimal(10,2) default null;
alter table item_trocas add column sub_total decimal(10,2) default null;
alter table credito_clientes add column troca_id integer default null;
alter table credito_clientes add column status boolean default 1;
alter table config_gerals add column usar_dropdown_acoes boolean default 0;
alter table caixas add column numero_sequencial integer default null;
alter table ordem_servicos add column marca varchar(100) default null;
alter table ordem_servicos add column modelo varchar(100) default null;
alter table config_gerals add column margem_lateral_impressao integer default 0;
alter table fatura_nfces add column codigo_autorizacao varchar(30) default null;
alter table fatura_nfces add column detalhes varchar(100) default null;
alter table fatura_nfces add column bandeira varchar(20) default null;
alter table users add column hora_inicio time default null;
alter table users add column hora_fim time default null;
alter table users add column dias_semana json default null;
alter table users add column bloquear_fora_horario boolean default null;
alter table acesso_logs add column acesso_bloqueado boolean default null;
alter table config_gerals add column tipo_pagamento_padrao varchar(2) default null;
alter table config_gerals add column ticket_troca boolean default 0;
alter table config_gerals add column mensagem_ticket_troca varchar(255) default null;
alter table nves add column fiscal_status enum('ok', 'alerta', 'erro') NOT NULL DEFAULT 'ok';
alter table nves add column fiscal_risco enum('baixo', 'medio', 'alto') NOT NULL DEFAULT 'baixo';
alter table nves add column fiscal_mensagens JSON NULL;
alter table produtos add column perc_red_bc_ibs decimal(10,2) default 0;
alter table nfces add column fiscal_status enum('ok', 'alerta', 'erro') NOT NULL DEFAULT 'ok';
alter table nfces add column fiscal_risco enum('baixo', 'medio', 'alto') NOT NULL DEFAULT 'baixo';
alter table nfces add column fiscal_mensagens JSON NULL;
alter table config_gerals add column limitar_cliente_inadimplente boolean default 0;
alter table ordem_separacaos add column prioridade enum('normal', 'urgente') default 'normal';
alter table config_gerals add column atualizar_valor_venda_importacao boolean default 1;
alter table clientes add column score_categoria enum('ouro','prata','bronze') default 'bronze';
alter table clientes add column score_limite_credito decimal(12,2) default 0;
alter table pedido_ifoods add column informacao_adicional varchar(255) default null;
